### ISSUE TITLE
关于 leanote docker

### ISSUE THREAD

**Issue by yangxuan8282** [izuolan/dockerfiles#2]
我尝试用你的 dockerfile build 了一下 leanote 2.4 版本，结果启动不起来

直接用你的 image 是没问题的，不知道为什么会这样

```
...
leanote_1  | INFO  2017/03/23 15:27:36 Debug.go:10: mongodb://127.0.0.1:27017/leanote
leanote_1  | panic: no reachable servers
leanote_1  | 
leanote_1  | goroutine 1 [running]:
leanote_1  | panic(0xa16a00, 0xc42038b590)
leanote_1  | 	/Users/life/app/go1.7/src/runtime/panic.go:500 +0x1a1
leanote_1  | github.com/leanote/leanote/app/db.Init(0xc420215c20, 0x21, 0x0, 0x0)
leanote_1  | 	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/db/Mgo.go:104 +0x48cb
leanote_1  | github.com/leanote/leanote/app.init.1.func28()
leanote_1  | 	/Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/init.go:423 +0x49
leanote_1  | github.com/revel/revel.runStartupHooks()
leanote_1  | 	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:164 +0x8e
leanote_1  | github.com/revel/revel.InitServer(0xa973e0)
leanote_1  | 	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:85 +0x34
leanote_1  | github.com/revel/revel.Run(0x0)
leanote_1  | 	/Users/life/Documents/Go/package_base/src/github.com/revel/revel/server.go:137 +0x220
leanote_1  | main.main()
leanote_1  | 	/Users/life/Documents/kuaipan/leanote/leanote-public/app/tmp/main.go:2312 +0x23239
24_leanote_1 exited with code 2
```

**Comment by izuolan** [comment]
试试这里面的：
https://github.com/izuolan/dockerfiles/tree/master/leanote/src

你运行退出是因为 mongoDB 没有启动或者已经退出。
`panic: no reachable servers`

**Comment by yangxuan8282** [comment]
谢谢，用 `dockerfiles/leanote/src` 目录下的文件可以启动 2.4 版本了
